// <auto-generated />
using Elections.App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elections.App.Migrations
{
    [DbContext(typeof(CandidateContext))]
    partial class CandidateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Elections.App.Database.Candidates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidateFirstName");

                    b.Property<string>("CandidateLastName");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Elections.App.Database.SettingApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVoteExposed");

                    b.HasKey("Id");

                    b.ToTable("SettingApp");

                    b.HasData(
                        new { Id = 1, IsVoteExposed = false }
                    );
                });

            modelBuilder.Entity("Elections.App.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CandidatesId");

                    b.Property<int>("UserPesel");

                    b.HasKey("Id");

                    b.HasIndex("CandidatesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Elections.App.Database.User", b =>
                {
                    b.HasOne("Elections.App.Database.Candidates", "Candidates")
                        .WithMany("Users")
                        .HasForeignKey("CandidatesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
